project:
  type: website
  output-dir: docs

website:
  title: "Bachelor Project"
  repo-url: https://github.com/twheed0seif/Bachelor-Project-SS
  issue-url: https://github.com/twheed0seif/Bachelor-Project-SS/issues/new/choose
  repo-actions: [edit, issue]
  search: true
  page-footer:
    left: |
      <div class="footer-container">
      <div class="supervised-by">
      <span>Proudly supervised by:</span>
      <a href="https://scholar.google.com.eg/citations?user=JebIw2QAAAAJ&hl=en">
        <span class="supervisor-name">Prof. Dr. Mohamed Farid Khalil</span>
        <img src="drfarid.svg" alt="Prof. Dr. Mohamed Farid Khalil" width="50" height="50" style="border-radius: 50%; overflow: hidden; margin-bottom: 10px;" />
        </a>
      </div>
      </div>
    right:
      - text: "About"
        href: about.qmd
      - text: "YouTube"
        href: https://www.youtube.com/watch?v=lH7vAzmmB-M
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
